/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: '#fcf8fa',
          dim: '#ddd9da',
          bright: '#fcf8fa',
          'container-lowest': '#ffffff',
          'container-low': '#f6f3f4',
          container: '#f1edee',
          'container-high': '#ebe7e8',
          'container-highest': '#e5e1e3',
        },
        'on-surface': {
          DEFAULT: '#1c1b1c',
          variant: '#47464c',
        },
        primary: {
          50: '#e8f5e9',
          100: '#c8e6c9',
          200: '#a5d6a7',
          300: '#81c784',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
        },
        'on-primary': '#ffffff',
        'primary-container': '#e8f5e9',
        'on-primary-container': '#1b3d22',
        'inverse-primary': '#81c784',
        secondary: '#595e6f',
        'on-secondary': '#ffffff',
        'secondary-container': '#dee1f7',
        'on-secondary-container': '#5f6475',
        tertiary: '#5d6234',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#e0e5ac',
        'on-tertiary-container': '#626739',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'brand-orange': '#F57C00',
        'brand-coral': '#FF7F50',
        'brand-peach': '#FF8A65',
        background: '#fcf8fa',
        'on-background': '#1c1b1c',
        outline: '#77767d',
        'outline-variant': '#c8c5cc',
        'inverse-surface': '#313031',
        'inverse-on-surface': '#f4f0f1',
        'surface-tint': '#4ade80',
        'success': '#2e7d32',
        'warning': '#f57c00',
        'danger': '#ba1a1a',
        'info': '#1976d2',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700', letterSpacing: '-0.01em' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600', letterSpacing: '0.05em' }],
        'metric-display': ['24px', { lineHeight: '24px', fontWeight: '700' }],
      },
      borderRadius: {
        DEFAULT: '1rem',
        sm: '0.5rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'container-padding': '24px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'gutter': '16px',
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        'blink': 'blink 1s step-end infinite',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.5s ease-out',
        'fade-in': 'fadeIn 0.5s ease-out',
        'scale-in': 'scaleIn 0.3s ease-out',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        blink: {
          '0%, 100%': { opacity: 1 },
          '50%': { opacity: 0 },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: 0 },
          '100%': { transform: 'translateY(0)', opacity: 1 },
        },
        slideDown: {
          '0%': { transform: 'translateY(-20px)', opacity: 0 },
          '100%': { transform: 'translateY(0)', opacity: 1 },
        },
        fadeIn: {
          '0%': { opacity: 0 },
          '100%': { opacity: 1 },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.9)', opacity: 0 },
          '100%': { transform: 'scale(1)', opacity: 1 },
        },
      },
    },
  },
  plugins: [],
};
