ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS height NUMERIC(5,1),
  ADD COLUMN IF NOT EXISTS weight NUMERIC(5,1),
  ADD COLUMN IF NOT EXISTS age INTEGER,
  ADD COLUMN IF NOT EXISTS gender TEXT,
  ADD COLUMN IF NOT EXISTS activity_level TEXT,
  ADD COLUMN IF NOT EXISTS budget TEXT,
  ADD COLUMN IF NOT EXISTS water_goal INTEGER,
  ADD COLUMN IF NOT EXISTS weight_goal NUMERIC(5,1),
  ADD COLUMN IF NOT EXISTS language TEXT DEFAULT 'en',
  ADD COLUMN IF NOT EXISTS notifications BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS email_updates BOOLEAN DEFAULT true;
